title: <p align="center"> Bhanu Prakash Doppalapudi</p>
logo: profile.jpg
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/bhanuprakash-doppalapudi-38b49489">LinkedIn</a> |
  <a href="https://github.com/bhanuprakashd">GitHub</a>
  
  <br>   
  I'm working on Data Science, NLP 
  </p>



theme: jekyll-theme-minimal
